---

- name: packages role
  include_role:
    name: packages
  vars:
    PKGS_LIST: "{{ IPTABLES_PKGS_LIST }}"

- name: reload iptables
  shell: |
    iptables -I INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
    iptables -I OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
    systemctl enable iptables
    iptables-restore < /etc/iptables/rules.v4    
  changed_when: false

- name: iptables config 
  template:
    src: etc/iptables/rules.v4.j2 
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart iptables

- name: Create directory if it does not exist
  file:
    path: /opt/internal_setup/
    state: directory
    mode: '0755'

- name: Copy internal scripts
  copy:
    src: opt/internal_setup/{{ item }}
    dest: /opt/internal_setup/{{ item }}
    owner: root
    group: root
  with_items:
    - setup.sh  
    - config 

