---

- name: packages role
  include_role:
    name: packages
  vars:
    PKGS_LIST: "{{ FAIL2BAN_PKGS_LIST }}"

- name: fail2ban config
  template:
    src: etc/fail2ban/jail.d/sshd.conf.j2
    dest: /etc/fail2ban/jail.d/sshd.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    restart fail2ban

